

###
# curl -X POST
#  http://localhost:8080/api/events/send/YOUR_SESSION_ID
#  -H "Content-Type: application/json"
#  -d '{"eventType": "TEST_EVENT", "payload": {"message": "Hello!"}}'
POST http://localhost:8080/api/events/send/nbpy1gnt
Content-Type: application/json

{
  "eventType": "TEST_EVENT",
  "payload": {
    "message": "Hello again!"
  }
}

###
###
# curl -X POST
#  http://localhost:8080/api/events/send/YOUR_SESSION_ID
#  -H "Content-Type: application/json"
#  -d '{"eventType": "TEST_EVENT", "payload": {"message": "Hello!"}}'
POST http://localhost:8080/api/events/broadcast
Content-Type: application/json

{
  "eventType": "TEST_EVENT",
  "payload": {
    "message": "Hello! broadcast"
  }
}

